apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
      - name: supermario
        image: pengbai/docker-supermario
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: supermario-service
  namespace: default
spec:
  selector:
    app: supermario
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30007
